[package]
name = "mavlink-test"
version = "0.1.0"
authors = ["TsuyoshiKawamura <kawamura@tajisoft.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mavlink = { version = "0.9", features = [ "ardupilotmega" ] }
